### ISSUE TITLE
Service resolution via Consul

### ISSUE THREAD

**Issue by minor-fixes** [buildbarn/bb-remote-execution#103]
As mentioned in the office hour - we're looking to resolve service addresses in the various configs via Consul, so that we don't need to use any dynamic templating system to look up IPs + ports; this would allow us to have static configs, which obviates the need to have config reloading logic inside buildbarn services or buildbarn reloading logic when the config changes (at least for our use case).

After some investigation, this should be possible with minimal intrusion in buildbarn code:
* buildbarn takes on a dependency on a [grpc Resolver](https://sourcegraph.com/github.com/grpc/grpc-go/-/blob/resolver/resolver.go?L277) plugin library
* buildbarn has an underscore import of the resolver plugin library somewhere; an `init()` in the plugin library registers a resolver for a custom scheme (effectively adding support directly to grpc for `consul://` URLs) NOTE: not all existing plugins support this, but they should IMO, and I could fork and add it)
* configs are rewritten to use `consul://` URLs; these are passed to the custom resolver by gRPC.

There are a [couple](https://github.com/mbobakov/grpc-consul-resolver) [resolver](https://github.com/simplesurance/grpcconsulresolver) [libraries](https://github.com/ekomobile/grpc-consul-resolver) that already exist, though they are of varying quality. 

One caveat is that there are (at least) two ways resolution can happen under the hood:
* via the Consul HTTP API. If this approach is used, the Consul HTTP API will apparently return services in a stable order, which means that the gRPC load balancing policy should be changed to "round_robin" in order to shard requests appropriately; this is called out in [various](https://github.com/mbobakov/grpc-consul-resolver/blob/9938c1db7ea3ee0c0aeb59a111b870be16a55cdc/README.md?plain=1#L50) [READMEs](https://github.com/simplesurance/grpcconsulresolver/blob/f1f1a150647eba709bbff69a12efcc8dc2fc846c/README.md?plain=1#L60) of the aforementioned plugins, and introduces another imposition on buildbarn code (unless customizing dial options is already plumbed up to the user configuration level?)
* via DNS SRV records. If the Go stdlib is used to do this, `LookupSRV` [does the right thing](https://pkg.go.dev/net#LookupSRV) in terms of randomizing order/respecting priority; no additional dial option should be necessary to change the load balancing policy away from the default "pick_first". However, [no plugins seem to exist](https://www.google.com/search?q=grpc-go+srv+resolver) yet that use SRV records.

What (if any) approach here would the buildbarn team be willing to consider to facilitate this usecase?
* adopt one of the Consul resolvers above as-is, provide a way to customize grpc dial options (or set automatically for certain schemes)
* adopt a fork of one of the Consul resolvers above, with fixes
* adopt a new resolver plugin that works off of SRV records, obviating concerns about the load balancing policy
* some other approach?

**Comment by EdSchouten** [comment]
Hey there! Sorry for not replying sooner. A change in this area is fine by me. With the config file format that we have, it's pretty easy to accommodate changes like these. Be sure to submit a PR!

**Comment by EdSchouten** [comment]
Considering that this issue hasn't seen any activity for almost 2 years, let's go ahead and close it. Contributions to integrate better with tools like Consul are still appreciated.
