### ISSUE TITLE
Buildbarn allows action to write under user home directory

### ISSUE THREAD

**Issue by ssingularity** [buildbarn/bb-remote-execution#110]
## Behavior
Buildbarn allows action to write under user home directory

## Specific Scene
here is an easy action to reproduce the scene
```
def _write_home_file_impl(ctx):
    out_file = ctx.actions.declare_file("a")
    ctx.actions.run_shell(
        outputs = [out_file],
        inputs = [],
        arguments = [out_file.path],
        command = "echo \"command exit not normally\" > ~/hello; echo 1 > $1",
    )
    return [DefaultInfo(files = depset([out_file]))]
```
bazel build local result:
```
INFO: From Action shell_command/a:
: /home/ziyi/hello: Read-only file system
```
while, bazel build remote with buildbarn successfully

## Probable Resolution
use `spawn_stratege=local` to run bazel command locally can make bazel allow action to write under user home directory, but it does not conform to bazel's concept while its default option is `sandbox`
I  have also seen `chroot_into_input_root` option in bb_worker, but it needs input root contains a full userland installation, and I think it is hard for my build process. So Is there any solution for the problem? Thanks!

**Comment by EdSchouten** [comment]
Whether or not that succeeds depends on how you set up your execution environment. Does the user under which you run bb_runner have write access to the home directory? If so, then your build actions will be able to write as well.

Just make sure to run bb_runner as an unprivileged user, or make use of the `runCommandAs` to let bb_runner do the switch for you:
https://github.com/buildbarn/bb-remote-execution/blob/fe0d449f520aa5ff02ccdc1a68a408ad6017bf94/pkg/proto/configuration/bb_runner/bb_runner.proto#L63-L64

Buildbarn will never gain "sandboxing" features like Bazel, for the reason that it is intended to run in a server environment, where the administrator can already make preparations for running the components in neatly isolated environments.

**Comment by ssingularity** [comment]
I initially assumed that bazel build local and remote will have same behavior without any additional configuration on buildbarn. I will update the image environment and ensure the users's privilige to solve it. Thanks for you help!
