### ISSUE TITLE
Linux sandboxing / network blocking

### ISSUE THREAD

**Issue by malt3** [buildbarn/bb-remote-execution#120]
When running build (and test) actions locally on Linux, Bazel can use Linux namespaces for sandboxing. This is implemented [here](https://github.com/bazelbuild/bazel/blob/master/src/main/tools/linux-sandbox.cc).

Is it correct that buildbarn currently does not implement sandboxing for actions? And if that is the case, would it be feasible to implement this?
I think bazel buildfarm can use `unshare` or the Bazel `linux-sandbox` wrapper to implement this and exposes options in the `exec_properties` to choose workers with the selected sandboxing applied.

**Comment by EdSchouten** [comment]
> Is it correct that buildbarn currently does not implement sandboxing for actions?

Indeed. But that's mainly because users can already configure their workers in such a way that they are sandboxed. For example, you can launch bb_runner inside a container that doesn't have any network access.

**Comment by malt3** [comment]
I see. I find it rather hard to come up with a Kubernetes worker deployment that correctly blocks networking without also preventing the connection between worker container <-> scheduler and worker container <-> storage. 
Would it be acceptable to add more examples in the deployments repo?

**Comment by EdSchouten** [comment]
Can't you change the startup command of bb_runner to be wrapped in 'unshare'?

https://man7.org/linux/man-pages/man1/unshare.1.html

**Comment by malt3** [comment]
That’s a good idea! Will give that a try. Thanks for the suggestion.

**Comment by EdSchouten** [comment]
Assuming this got solved, let me close this issue. Thanks for reaching out!

**Comment by malt3** [comment]
It is fine to close this, but I want to make sure to not confuse future users (or myself):
BuildBarn currently does not implement fine-grained sandboxing / network blocking.
As mentioned above, it is possible to do restrict the worker process itself.
Thanks again for the ideas!
