### ISSUE TITLE
Missing output files are ignored by bb-worker

### ISSUE THREAD

**Issue by ulrfa** [buildbarn/bb-remote-execution#128]
We had an action that incorrectly returned exit code 0, despite that it failed to create all output files in a situation when a bb-worker was running out of disk space. The result was cached, causing numerous subsequent builds to also fail. Removing the malfunctioning bb-worker server would not help, since the result was already cached.

The root cause is indisputably the action incorrectly returning exit code 0. However, can we make Buildbarn cope with that more gracefully, by not returning status OK in the ExecuteResponse if output files are missing?

The current logic in https://github.com/buildbarn/bb-remote-execution/blob/28dbdbb0a6b077cb7f987393ce537b603da3d045/pkg/builder/output_hierarchy.go#L147 is doing the opposite and explicitly ignore issues caused by missing files. What is the reason for ignoring missing output files?

**Comment by EdSchouten** [comment]
> However, can we make Buildbarn cope with that more gracefully, by not returning status OK in the ExecuteResponse if output files are missing?

No. There is no requirement that an action yields all output files/directories. Take a look at Bazel tests, invoked through `test-setup.sh`. Those actions have about a dozen output files. Many of them are missing in the common case.

**Comment by ulrfa** [comment]
OK, I see. Thanks for quick answer!
