### ISSUE TITLE
Better Logging

### ISSUE THREAD

**Issue by finnball** [buildbarn/bb-remote-execution#14]
Buildbarn's logging isn't great.

I propose we improve it. One method could be to use a gRPC interceptor and log all calls made. This would have the benefit of minimal disruption to the core code.

Any thoughts or suggestions on how to implement this?

**Comment by mickael-carl** [comment]
Hi there!

Some time ago, a PR was submitted to add [opencensus support in bb-storage](https://github.com/buildbarn/bb-storage/pull/10). Rather than adding another layer just for logging the prefered way for logging would instead be to use opencensus where needed. 
So now it would only be a matter to reuse those bits and apply to the rest of Buildbarn.

**Comment by ailiev** [comment]
A theoretically code-free way to get gRCP logging https://github.com/grpc/proposal/blob/master/A16-binary-logging.md

Unfortunately implementations of this are not complete. I was able to get some logs with [a couple of lines in buildbarn and a small patch to grpc-go (via rules_go)](https://github.com/ailiev/bb-storage/commit/c5edb46d6f59e0532c0c8a7024705027ab8def51). Currently trying to decode the log obtained this way.

**Comment by EdSchouten** [comment]
I am going to mark this one as closed. Over the last half year, many improvements have been made. Not necessarily in the area of logging, but error propagation and messages are a lot better than they used to be. There's also better support for tracing.

I am not a fan of making Buildbarn spammy. Logging should only be done in cases where errors cannot be propagated up to the user. Fortunately in the case of Buildbarn, (almost?) all of the work is triggered by user-initiated RPCs.

If there's a lack of information exposed by Buildbarn, let's open individual pull requests/issues to discuss those scenarios in more detail. The outcome of those discussions will likely be improving error message formats or adding more trace points.
