### ISSUE TITLE
Use the Remote Worker API instead of a custom protocol... or not?

### ISSUE THREAD

**Issue by EdSchouten** [buildbarn/bb-remote-execution#2]
At the Bloomberg Build Event and FOSDEM earlier this month, we chatted about convergence of remote worker protocols between Buildbarn and BuildGrid. Even though RWAPI would be the most obvious choice, it was mentioned that the authors of this protocol have less interest in using it externally than initially anticipated.

@buchgr stated that he is going to see whether he can get RWAPI moved to https://github.com/bazelbuild/remote-apis. When imported, we should hold discussions to see whether the protocol can be simplified. Once that's done, we should alter bb-scheduler and bb-worker to use that protocol instead.

Old tracking bug: https://github.com/EdSchouten/bazel-buildbarn/issues/7

**Comment by jjardon** [comment]
Hi, is there any further movement on this area?

Seems the RWAPI is not at https://github.com/bazelbuild/remote-apis yet

**Comment by EdSchouten** [comment]
Hi Javier,

@buchgr mentioned earlier this week he's still dealing with Google internal politics getting this moved over. He pinged some of the other people involved once again, so let's hope some progress is achieved one of these days/weeks.

**Comment by finnball** [comment]
if it does happen, do you plan on implementing soon or is it something lower priority for you?

**Comment by buchgr** [comment]
> let's hope some progress is achieved one of these days/weeks.

My guess is that it will be months but the most current version (the one that needs to go through review) of the API is https://github.com/googleapis/googleapis/tree/master/google/devtools/remoteworkers/v1test2 and so we could still make progress by implementing this version, as I'd expect there to only be very minor changes being requested during the review.

**Comment by EdSchouten** [comment]
Discussion going on here: https://groups.google.com/forum/#!msg/remote-execution-apis/QLJvYKd5_gw/8rVVbLUmBgAJ

**Comment by EdSchouten** [comment]
The outcome of all of this is that Buildbarn now has an improved protocol that works incredibly well. It is up to other implementations to decide whether they want to adopt something it too.
