### ISSUE TITLE
Move input root to sub directory of build directory

### ISSUE THREAD

**Issue by Qinusty** [buildbarn/bb-remote-execution#20]
That said, one change we should consider making to Buildbarn at some point is that we do move the input root into some kind of subdirectory, reserving the top-level directory for other storage purposes. For example, stdout and stderr of build actions are currently stored as files inside the input root. So like this:

```
input_root
├── .stdout.txt
├── .stderr.txt
├── input_file.c
└── output_file.o
```
Though most build actions generally don't care about that, it's a bit sloppy. If a build action would try to `tar` its entire input root, it would also archive its own stdout/stderr logs. We should consider restructuring it to something like this:
```
build_directory
├── stdout.txt
├── stderr.txt
└── input_root
    ├── input_file.c
    └── output_file.o
```

_Originally posted by @EdSchouten in https://github.com/buildbarn/bb-remote-execution/issues/18#issuecomment-525313758_

**Comment by Qinusty** [comment]
When doing this, it will be important to ensure that we alert the runner to the input_root, I propose doing this through adding a simple field to `runner.proto` like [here](https://github.com/Qinusty/bb-remote-execution/commit/381923ed4516196bd286a24f667ed2d8581d81d5#diff-0faee26f341a0afbfba0c4fda0fe348aR42).

Following this, it will be important to ensure that the action is executed from within the input_root to ensure that any provided toolchains are used. Buildstream supplies a full sandbox environment for actions as input files and as such `autoconf` may be expected to exist under `$PATH`, which could be placed at `/bin`, `/usr/bin` etc.

**Comment by EdSchouten** [comment]
This has been fixed now. Builds take place in a `root` subdirectory. The stdout and stderr logs are no longer prefixed with a dot, making it easier to find them.
