### ISSUE TITLE
bb_runner: Allow it to chroot into the input root

### ISSUE THREAD

**Issue by Qinusty** [buildbarn/bb-remote-execution#23]
This comes as a proposal to implement behavior which is currently outside of the REAPI spec but is seen as an additional non standard platform property within RBE.

The proposal is that the worker/runner be provided with an optional platform property allowing the client to request that the action be executed within a sandbox within the input root. Currently this is the case but this is simply coincidental that the build directory is also the input root currently (See #20).

**Comment by Qinusty** [comment]
This was briefly disuccsed on the #buildstream IRC on gimpnet on 04/09/2019 by @juergbi and @Kinnison.

```
...
10:13 <juergbi>  to support buildstream clients, the server/worker either has to directly support this extra chroot, e.g., triggered via platform property
10:13 <juergbi>  or buildstream has to use chroot as action command
10:14 <Kinnison>  juergbi: the latter requiring that the action run as root presumably
10:14 <juergbi>  yes, although it can be root in a user namespace, or we could use bwrap instead of chroot
10:15 <juergbi>  however, it's not so easy to do it right as this is a platform-specific thing, of course
10:15 <juergbi>  my preferred solution would be a platform property in standard REAPI that will trigger this on the server/worker side
10:16 <juergbi>  right now REAPI is underspecified in this regard. if you just use what's in the spec, the client has no idea what kind of environment the action will run in
10:16 <juergbi>  what path, what tools will be available etc.
10:16 <juergbi>  this generally can't work, also not for bazel
10:16 <juergbi>  Google RBE has a (non-standard) platform property to allow specifying a docker image for the action to run in
10:17 <juergbi>  that is theoretically good enough (but it's still a bit inconvenient for buildstream as it's platform specific, and doesn't work at all on non-Linux)
10:18 <juergbi>  we should probably make a proposal for such a platform property
10:18 <juergbi>  and ideally provide patches for buildbarn and buildfarm
10:19 <juergbi>  or at least bring it up on mailing list or in the monthly meeting
10:20 <qinusty>  And this would be a modification to the REAPI proto?
10:22 <juergbi>  addition
10:22 <juergbi>  could be part of the platform lexicon, i.e., considered optional to implement
```

**Comment by EdSchouten** [comment]
Renamed this issue to explicitly mention the chroot use case. Stuff like respecting the `container-image` label is out of scope for this issue, as I think that should be done as part of #40.

**Comment by EdSchouten** [comment]
This should be easy to implement now. The runner protocol now has a dedicated field that provides you the input root directory:

https://github.com/buildbarn/bb-remote-execution/blob/5df73f069a4f65ebc3699fe4696f0699bffc6d0f/pkg/proto/runner/runner.proto#L45-L46

That is the directory in which you should chroot.

**Comment by EdSchouten** [comment]
We now have chroot support. 🎉
