### ISSUE TITLE
Unable to access GCS due to missing certs

### ISSUE THREAD

**Issue by henryaj** [buildbarn/bb-remote-execution#24]
Hi!

We're seeing problems when using GCS as a storage backend; specifically errors like:

```
Get https://storage.googleapis.com/<bucketname>/buildbarn-cas/<some-hash>:
oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: x509:
certificate signed by unknown authority
```

Is this fixable with a simple `apt-get install ca-certificates` or similar? Notably not all the images seem to have this problem; specifically we see this error when doing remote execution (as opposed to remote caching, which works fine).

**Comment by EdSchouten** [comment]
The container images now use the rules_docker go_image() as their base image. This means they now include CAs properly. Marking this as closed. Thanks for reporting this issue!
