### ISSUE TITLE
Load Balancing and Redundancy without Proxy

### ISSUE THREAD

**Issue by ulrfa** [buildbarn/bb-remote-execution#30]
Hi,

One way to get load balancing and redundancy is to use proxies (like bb_storage with sharding, mirroring, etc).

- But passing all traffic through proxies increases **latency** and resource consumption.

- For me it also causes additional problems, since our machines typically have 2 x 10 Gbit/s network interfaces combined into 20 Gbit/s with ethernet bonding. The underlying interface is chosen based on hash of the TCP source port, resulting in unbalanced load, especially since the bb_storage proxy opens only a single TCP connection to each cache instance.

Another approach could be to let the **bazel client side control the load balancing** and choose a cache instance. And then connect directly to the bb_scheduler and tell which cache instance to use for each action.

- Perhaps bb_scheduler and bb_worker could connect to alternative cache instances, based on the instance_name, in the current remote execution protocol from the client?

What do you think?

Regards,
Ulrik Falklöf

**Comment by EdSchouten** [comment]
I think it would be unwise to add actual logic to Bazel to do the sharding and mirroring, as that logic is quite specific to Buildbarn and not standardized/stabilized in any way.

In your case you could consider just running a bb-storage instance on every client system, right? Bazel could be configured to speak REv2 against localhost.

Alternatively, we could add logic to bb-storage to open multiple connections to a gRPC backend. That would reduce the bonding/link aggregation imbalance you are seeing.

**Comment by ulrfa** [comment]
Thanks for your instant response!

I agree about not exposing logic or concepts from Buildbarn to Bazel. What I imagine is to let the client have its own way of choosing a gRPC bazel cache address to connect to. In most simple case just selecting one by random from a list, and if not responding pick another one. Or more advanced selection algorithms to increase cache hit ratio. That should provide load balancing and redundancy.

It seems gRPC also has some built in support for client side load balancing: https://github.com/grpc/grpc/blob/master/doc/load-balancing.md.

If replication is desired, that could be realized by queuing asynchronous updates between different cache servers, similar to how https://github.com/buchgr/bazel-remote can do, without involving the client.

The client had to communicate the chosen cache gRPC address to bb-scheduler. Perhaps the instance name in the REv2 ExecuteRequest could be one way of doing that.

I could consider running bb-storage proxies on each client. But many of our client machines are weak, only two or four cores, and are already struggling to feed workers in a large cluster. And always sending all traffic through a proxy seems inefficient.

**Comment by ulrfa** [comment]
Now I tried bb-storage proxy on client system. But it **more than doubled the total build time**. Our client machines only have four cores and were already struggling to feed workers in a large cluster. Their CPUs are overloaded when also running bb-storage proxy.

I also tried reducing the bonding/link aggregation imbalance by configuring many shards towards the same gRPC address, and also by referencing an remote HTTP blobstore. Both alternatives addresses the imbalance, but even if the proxy is deployed on a separate powerful machine, close on the network, **the extra latency still increased the build time with 10%** for some scenarios.

Therefore I think it would be attractive to **avoid the proxy, and let the bazel client side choose one of several gRPC addresses and connect to it directly.**

If not accepted into the official bazel client, the logic for choosing a bazel cache instance might even be done by a wrapper script that then just passes choosen --remote_cache=… and --remote_instance_name=… to the bazel client. But it would require bb-scheduler and bb-worker to connect towards the same blobstore as the client. One way of doing that might be to let **bb-scheduler and bb-worker have different blobstores depending on the instance name in the REv2 ExecuteRequest.**

What do you think?

**Comment by EdSchouten** [comment]
Out of curiosity, are you using [‘Builds without the Bytes’](https://github.com/bazelbuild/bazel/issues/6862)?

**Comment by ulrfa** [comment]
We are currently not using "Remote Builds without the Bytes". The feature certainly has potential but seems too fragile as it is now.

I would prefer if the client could cope with absent objects in CAS, instead of requiring special handling in the caches (such as CompletenessCheckingBlobAccess).

And I got the impression that even with such special handling in place, 'bazel clean' would still occasionally be needed (however I have not tried it recently). I want users to trust the build system, and not fall back to old habits of 'make clean'.

**Comment by EdSchouten** [comment]
I’m going to close this, as there is little that is actionable on our end. In my opinion:

- Tools like Bazel should work towards making Builds without the Bytes more robust.
- In addition to that, Bazel should add more mechanisms for having Builds without the Bytes, but not with the disadvantages. It would be nice if you could still just explore bazel-out/ and load outputs on demand.
- If there is still a need for client-side sharding, that’s something that should be tackled as part of the remote-apis working group. That way Bazel and Buildbarn can both implement this in a compatible way.
