### ISSUE TITLE
Call gazelle instead of buildifier in CI pipeline

### ISSUE THREAD

**Issue by cphang99** [buildbarn/bb-remote-execution#37]
Something I should have brought up in your previous PR: would it be possible to call Gazelle instead of Buildifier here? Gazelle automatically does a Buildifier, so there is no need to do both. That said, let’s already go ahead and merge this.

_Originally posted by @EdSchouten in https://github.com/buildbarn/bb-remote-execution/pull/36#issuecomment-590070040_

**Comment by EdSchouten** [comment]
Fixed in https://github.com/buildbarn/bb-remote-execution/commit/3914c2335e658f0e8a35f43f13b6ae84791db6b8
