### ISSUE TITLE
Schedule actions based on invocation id

### ISSUE THREAD

**Issue by ulrfa** [buildbarn/bb-remote-execution#38]
It is often better to finish work instead of letting new work in.

## Example

1.	Bazel client A submits a batch of actions to remote queue.
2.	Then bazel client B submits a huge batch of actions. They are queued waiting to be executed.
3.	Then client A submits a small final set of actions for its session.
4.	Then client B submits many more actions.

#### Current behavior

Actions submitted in step 2 are executed before actions from step 3.

#### Wanted behavior

The actions submitted by client A in step 3, should be executed before queued actions from client B in step 2. Because that would allow the already started client A to finish, and therefore reduce the average latency of completed build sessions.

## Suggestion for bb-scheduler

- Keep track of initial QeueuedTimeStamp for each new bazel invocation (a.k.a. `tool_invocation_id` in REv2). Call it **invocationTimeStamp** and associate it with the `tool_invocation_id`.

- Sort actions in queue based on:
           1. Priority
           2. **InvocationTimeStamp**
           3. QeueuedTimeStamp

- Create some mechanism for discarding information about old `tool_invocation_ids`.

## Discussion

It could be argued that bb-scheduler can’t know if client B has much less remaining work to do than A, and would finish earlier if given a chance. That could be a reason for allowing a limited set of resources also to B, before A is finished. But that might be hard to accomplish without making the queue algorithm much more complex. And the need for such complexity would be reduced if actions can be executed both locally and remotely and taking result from what finishes first, like bazels `--experimental_spawn_scheduler` option.

With other proprietary solutions, we experienced that a client machine could become an bottleneck for the whole cluster, if not balancing actions from several clients, but that should not occur with bazel remote execution, since actions are not queued until after their input files have been uploaded.

An alternative could be to use `correlated_invocations_id` instead of `tool_invocation_id` in REv2.

What do you think?

**Comment by EdSchouten** [comment]
I'm going to close this, as it's unlikely that work is going to be done to satisfy this use case. The reason being:

> It is often better to finish work instead of letting new work in.

This contradicts with what I've observed on my end. People may schedule the weirdest builds that end up hogging resources. Letting the scheduler be fair ensures that a decent amount of resources remain available, even if there are one or more builds that make little forward progress.

Furthermore, with the fairness that we have implemented right now, builds that only require rebuilding a small number of actions can effectively 'overtake' the large builds. I think this is a very desirable property in practice:
- People who make tiny one-line changes want to get a pass in CI quickly.
- People who schedule builds that cause entire rebuilds (e.g., by bumping a toolchain) generally don't mind waiting.

Effectively running all builds sequentially means that people in the former group may need to wait for a very long time.
