### ISSUE TITLE
bb-scheduler web view listing sessions

### ISSUE THREAD

**Issue by ulrfa** [buildbarn/bb-remote-execution#39]
The bb-scheduler has already a web view listing individual operations/actions. But an additional view listing bazel client invocations, instead of the individual operations/actions they consist of, would give a much better overview to understand what is going on in the cluster.

## Example of a new view listing bazel invocations

Invocation Id | First Action | Priority | Queued Actions | Executing Actions | Finished Actions | Failed Actions | Keywords
-------------|--------------------|-----|----|--------|------|-------|-------------
d252ce12… |2020-02-25 15:44 |  10 |      |           | 1202  |      2 | host=machine3 user=bob
182bfe59…  |2020-02-25 16:13 |   0  | 82 |     28  |  301  |         |host=machine7 user=alice
372bce18… |2020-02-25 16:14 |    0 | 53 |          |          |          |host=machine3 user=bob

#### Notes about each column:
* **Invocation Id**: tool_invocation_id field in REv2 protocol.
* **First Action**: Queue time for first action with this invocation id.
* **Priority**:  E.g. of the first action with this invocation id.
* **Queued Actions**: Number of actions currently waiting in queue with this invocation Id.
* **Executing Actions**: Number of currently executing actions with this invocation Id.
* **Finished Actions**: Number of finished actions with this invocation Id.
* **Failed Actions**: Number of failed actions with this invocation Id.
* **Keywords**: Perhaps derived from information passed via bazel’s new `--remote_exec_header` option.

There should also be:

* a link for listing all individual operations/actions, for a particular Invocation Id.
* a button for aborting all actions with a particual invocation id.

Optionally there could also be a link to a bb-browser web interface for the particular invocation Id, but all builds handled by bb-scheduler might not be using BES and should still be shown in the bb-scheduler view.

**Comment by EdSchouten** [comment]
Hi Ulrik,

Though I think having a page that displays information like this would be awesome to have, we should be careful with adding stuff like that to bb-scheduler itself. The idea right now is that bb-scheduler only displays information that it needs for its own bookkeeping. Aggregating data based on invocation ID, together with counters based on historical execution is something that isn't strictly needed to schedule build actions, right?

That said, it would make sense to add some kind of hooks mechanism to bb-scheduler, so that it could post build action execution events to some helper service (e.g., a more advanced system that combines this information with BES).

**Comment by ulrfa** [comment]
Hi Ed,

Perhaps new counters could be avoided, and instead be derived from existing bookkeeping data, if letting the session view show only numbers for queued and executing actions (and possibly recent actions that has not yet passed the OperationWithNoWaitersTimeout). And handle historical data by a separate service, as you describe.

However, an invocation ID string would still have to be added to the operation struct, but I guess that would be needed also if only posting events to separate service. And it is in line with the already existing argv0 string, right?

A mapping from invocation ID to InvocationTimeStamp would be needed also for scheduling, if implementing https://github.com/buildbarn/bb-remote-execution/issues/38, right?

What is remaining then is the keyword information. I agree it does not belong in bb-scheduler, but could it be accepted as a workaround until a separate service is available?

Do you think a button for aborting all actions of a particular invocation id, should be part of a bb-scheduler web view? Or should a separate service send events to bb-scheduler for aborting sessions?

**Comment by Qinusty** [comment]
I was recently thinking about this myself, having started to run into more and more situations where I need to get hold of ActionResults (in browser) for successful actions, this would be an incredible tool for tracking a list of actions for a given bazel build.

Whilst Scheduler could likely provide an option to filter operations by invocation id, I think @EdSchouten is likely right that keeping any sort of history of this in the scheduler will be unnecessary and bloat the service slightly, but I'd be keen to see some external service (maybe even browser) provide a lookup for actions based on invocation id.

Alternatively, we could work to integrate with [buildbuddy](https://github.com/buildbuddy-io/buildbuddy/issues/15) to provide some way to access actions from the bazel invocation. (Although this requires BES and is limited by the strangely restrictive BEP)

**Comment by EdSchouten** [comment]
I think this has effectively been completed at this point. By using invocation key extractors, you can partition operations by user, correlated invocations ID, and tool invocation ID. Various facilities for filtering exist. See this ADR for more details:

https://github.com/buildbarn/bb-adrs/blob/master/0007-nested-invocations.md

Maybe it's possible to make improvements here and there, but I think those should be filed as separate issues.
