### ISSUE TITLE
Avoid scheduling two identical actions on the same worker

### ISSUE THREAD

**Issue by Qinusty** [buildbarn/bb-remote-execution#43]
Currently it is possible for two actions marked `doNotCache` to hit the same worker. These actions cannot be deduplicated but can cause issues due to the deterministic action subdirectory naming convention.

To avoid having builds fail in this case, the scheduler should avoid scheduling two identical actions onto the same worker.

Example failure:

```
Note: Remote connection/protocol failed with: execution failed java.io.IOException: com.google.devtools.build.lib.remote.ExecutionStatusException: INTERNAL: Failed to acquire build
environment: Failed to create build subdirectory "e3414cebacf640db": file exists
```

**Comment by EdSchouten** [comment]
Random thought: DoNotCache actions are, as the name implies, not cached. Maybe it's not that important that we execute these in a deterministic fashion? We could fall back to random directory name generation in case DoNotCache is set...

**Comment by EdSchouten** [comment]
Fixed in https://github.com/buildbarn/bb-remote-execution/commit/94b9fb6e56831dfafd81ce1853a6f86be234f36f
