### ISSUE TITLE
Don't clean all build directories between runner completions (only clean completed runner directory)

### ISSUE THREAD

**Issue by allada** [buildbarn/bb-remote-execution#51]
Our setup looks something like this:
- Worker with ~16 runners.
- Each runner gets its own connection to worker (ie: each runner is set `concurrency=1`)

We do not use concurrency because it waits for all jobs to finish on that runner before fetching more jobs.

This setup however doesn't work because every time a worker's job finishes it will cause the build directory to be cleaned up here:
```go
func (d cleanBuildDirectory) Close() error {
	err := d.BuildDirectory.Close()
	d.initializer.Release()
	return err
}
```
However, it appears that we already cleanup the build directory after each job finishes. Currently we can just comment out these lines and `dc.initializer.Acquire(buildDirectory.RemoveAllChildren)`  which causes it to never clean up between jobs at the risk of if a runner dies it may leave a file forever.

Our use-case doesn't have this as an issue because we handle failure cases aggressively and just terminate the node if it has too many failures (and we terminate nodes if they are running more than a set amount of time).

I see two major ways to upstream this.
1. We can make a configuration simply instruct it to not clean the directory between runs (let each worker completion do it [which already happens]).
2. Make a kind of locking system with folder garbage collection. But this seems complicated and likely will result in edge cases.

**Comment by EdSchouten** [comment]
Wait. Are you sure about that?  It shouldn't. Notice how `NewCleanBuildDirectoryCreator()` takes a `sync.Initializer`. That object is responsible for doing reference counting on the build directory.

Notice how `cmd/bb_worker/main.go` creates exactly one `sync.Initializer` for this purpose. All of the CleanBuildDirectoryCreator instances in bb_worker thus share a single reference count.

**Comment by allada** [comment]
Yep, I am wrong. I have confirmed that the issue I was experiencing is related to an issue I as having with eventual-consistency.
