### ISSUE TITLE
Support GetOperation function of Operations API

### ISSUE THREAD

**Issue by tdyas** [buildbarn/bb-remote-execution#57]
BuildBarn does not appear to implement the GetOperation function in the Google Operations API. The [Pants build tool](https://github.com/pantsbuild/pants) assumes that the remote execution server implements this function (which Pants uses to poll for request completion), and thus Pants can submit a request to a BuildBarn instance, but immediately gets back an `UNIMPLEMENTED` gRPC error when it calls `GetOperation`.

The remote execution specification [would seem to require implementing GetOperation (but not other Operations API functions)](https://github.com/bazelbuild/remote-apis/blob/7802003e00901b4e740fe0ebec1243c221e02ae2/build/bazel/remote/execution/v2/remote_execution.proto#L70-L78):

>If the client remains connected after the first response is returned after
>the server, then updates are streamed as if the client had called
>[WaitExecution][build.bazel.remote.execution.v2.Execution.WaitExecution]
>until the execution completes or the request reaches an error. The
>operation can also be queried using [Operations
>API][google.longrunning.Operations.GetOperation].
>
>The server NEED NOT implement other methods or functionality of the
>Operations API.

Is there any reason why GetOperation is not implemented? If not, any objection if I submit a PR to implement it?

I'm tracking the Pants-side of this at https://github.com/pantsbuild/pants/issues/9876.

**Comment by EdSchouten** [comment]
Hey Tom,

The only reason why it's not implemented is because the initial attempt was to just focus on the parts that Bazel uses. Bazel only calls Execute() and WaitExecution(), so there was no need to provide GetOperation(). I am fine with adding support for GetOperation(), as REv2 requires it. Adding support for other Operations methods doesn't seem like a good idea in my opinion.

With regards to cancelation (also stated in the PR you linked), there's no need to worry about that when using Buildbarn. Canceling Execute() and WaitExecution() calls on the client already causes the scheduler to abort operations after a minute or so. The scheduler is only willing to hold on to operations if one or more clients are using them.

**Comment by EdSchouten** [comment]
That said, important to mention: If the plan is to change Pants to use Execute() + WaitExecution() anyway, don't feel obliged to add support for GetOperation() to Buildbarn. In my opinion it's good to focus on those parts of the spec that are actually used in practice. Removing features in the future (e.g., REv3) is harder than adding stuff.

**Comment by tdyas** [comment]
> With regards to cancelation (also stated in the PR you linked), there's no need to worry about that when using Buildbarn. Canceling Execute() and WaitExecution() calls on the client already causes the scheduler to abort operations after a minute or so. The scheduler is only willing to hold on to operations if one or more clients are using them.

So if a client closes the `Execute` call's result stream (or `WaitExecution`''s result stream), will Buildbarn treat that as a cancellation?  Seems like Pants may need to use `Execute` / `WaitExecution` just so there is an open result stream to let Buildbarn know that there is still an interested client.

**Comment by tdyas** [comment]
> In my opinion it's good to focus on those parts of the spec that are actually used in practice

Do you know offhand of any comparisons showing what parts of REv2 various servers and clients implement? (If not, I'm leaning to developing one just for my own education.)

**Comment by EdSchouten** [comment]
> So if a client closes the `Execute` call's result stream (or `WaitExecution`'s result stream), will Buildbarn treat that as a cancellation? Seems like Pants may need to use `Execute` / `WaitExecution` just so there is an open result stream to let Buildbarn know that there is still an interested client.

It won't be treated as an immediate cancellation. But if the client doesn't perform another Execute() call (that gets in-flight deduplicated) or WaitExecution() call within the minute that follows, the operation is cancelled. Buildbarn simply refuses to hold on to work if no clients are willing to continue engaging.

> Do you know offhand of any comparisons showing what parts of REv2 various servers and clients implement? (If not, I'm leaning to developing one just for my own education.)

Unfortunately, I do not. I do know that Bazel doesn't use any of the `Batch*Blobs()`. BuildStream does use them. I am not aware of any clients using CAS.GetTree() and Bytestream.QueryWriteStatus().

**Comment by tdyas** [comment]
Closing as the solution points at improving the Pants REv2 client.

**Comment by EdSchouten** [comment]
Good luck with that! Feel free to reach out if you folks have any other questions!
