### ISSUE TITLE
Buildbarn needs to run as root for some reason

### ISSUE THREAD

**Issue by Monnoroch** [buildbarn/bb-remote-execution#58]
I've encountered an interesting issue.

Here's the error I got when running a remote build:
```
ERROR: ${HOME}/${REPO}/${PATH}/BUILD.bazel:6:1: Extracting AndroidManifest.xml from ${TARGET}.aar failed (Exit -1): zipper failed: error executing command 
  (cd ${OUTPUT_BASE}/execroot/${REPO} && \
  exec env - \
    BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 \
    PATH=/bin:/usr/bin \
  bazel-out/host/bin/external/bazel_tools/third_party/ijar/zipper x bazel-out/k8-fastbuild/bin/${PATH}/${TARGET}.aar -d bazel-out/k8-fastbuild/bin/${PATH}/_aar/${TARGET} AndroidManifest.xml)
```

Upon debugging I traced it to [this code](https://github.com/bazelbuild/bazel/blob/4827fc672e4cd0ccb943120a1707c88c21634809/src/main/cpp/util/file_posix.cc#L69). (Bazel 3.1.0). Bazel checks permissions of the directory being created and fails because `geteuid() == ` [65534](https://github.com/buildbarn/bb-deployments/blob/0e52bf30d69c76413b5bd5151bd6187916cc421c/kubernetes/worker-ubuntu16-04.yaml#L45) but `linkstat.st_uid == 0` (root). When I run the bb-runner as root (i.e.`runAsUser: 0`) everything builds successfully.

Stack trace for more context:
- [GetDirectoryStat](https://github.com/bazelbuild/bazel/blob/4827fc672e4cd0ccb943120a1707c88c21634809/src/main/cpp/util/file_posix.cc#L69)
- [MakeDirectories](https://github.com/bazelbuild/bazel/blob/4827fc672e4cd0ccb943120a1707c88c21634809/src/main/cpp/util/file_posix.cc#L90)
- [UnzipProcessor::Process](https://github.com/bazelbuild/bazel/blob/4827fc672e4cd0ccb943120a1707c88c21634809/third_party/ijar/zip_main.cc#L127)

And the log:
- `f 777 AndroidManifest.xml` [here](https://github.com/bazelbuild/bazel/blob/4827fc672e4cd0ccb943120a1707c88c21634809/third_party/ijar/zip_main.cc#L122)

What do you think could be the cause of this issue? The output directory for the zipper is created by some bazel internals or maybe the runner, not manually by user code in rules, so I doubt it's a bug I can fix in my repository. I could provide an example, but it's going to take me a while to create a minimal one and strip all the internal code I can't share. Perhaps you have ideas from just knowing the issue is about output directory permissions?

**Comment by EdSchouten** [comment]
That's interesting. I suspect I never ran into this, because it only affects certain kinds of build actions (Android related) that I've never used?

In my opinion this is an issue with Bazel itself. Nowhere in the Remote Execution specification do they state any requirements that files/directories created in the input root are owned by the calling process. Could you maybe file an issue against Bazel to report this? Thanks!

**Comment by Monnoroch** [comment]
Well, I could do that, but I don't think I would be able to defend this argument very well. I'm not at all familiar with remote build specs. Would probably be much more efficient if someone who speaks the spec language would do it.

**Comment by EdSchouten** [comment]
I've never run into these issues personally, so I also wouldn't be the right person to report this.

I'm going to close this, as there is nothing actionable on the Buildbarn side.
