### ISSUE TITLE
Empty input directories are omitted

### ISSUE THREAD

**Issue by Monnoroch** [buildbarn/bb-remote-execution#59]
Rules proto grpc project [runs](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/627741e7c310ebc316d85a4843ddca5b7604ca77/aspect.bzl#L79) `cp -r` on multiple input directories. Each directory is created by an aspect for a `proto_library` target. During local execution Bazel creates output directories defined by `declare_directory()` for aspects and then calls the action to populate them. If the action doesn't produce any files empty directories stay as they were. When the same build is executed remotely with Buildbarn empty directories are not present in the inputs (while non-empty ones are there). I assume this is a bug in Buildbarn -- it doesn't download empty directory trees. #47 makes me think that if there's no files the directory tree will not be built. Since `declare_directory()` was called I would expect it to be present in dependent actions no matter it's contents.

**Comment by Monnoroch** [comment]
Any comments on this issue? Is it considered a bug of the buildbarn implementation or should I file a PR to the proto rules repo?

**Comment by EdSchouten** [comment]
Can you check whether this still holds with the latest copy of Buildbarn? It may be that this was related to #46. Be sure to also explore the input root in bb-browser. If there is no directory there, then there is little we can do; Bazel doesn’t provide it to us then.

**Comment by Monnoroch** [comment]
Nope, still the same problem.

**Comment by EdSchouten** [comment]
Have you inspected bb-browser to see what the input root looks like?

**Comment by Monnoroch** [comment]
Yes, it doesn't have the empty directories. Only directories with files in them.

**Comment by EdSchouten** [comment]
Then in that case Buildbarn is working as expected. It instantiates the file system as provided by Bazel. Be sure to file a new issue against Bazel itself to report this issue!
