### ISSUE TITLE
CI Testing

### ISSUE THREAD

**Issue by finnball** [buildbarn/bb-remote-execution#6]
The Buildbarn project has no CI testing.

We should have CI testing which ensures every commit has tests run, formatting, linting etc. Eventually posting code coverage and if the build is passing.

**Comment by mickael-carl** [comment]
A first CI plan is up which builds and runs `bazel test`! Now to actually add more features. Things I can come up with:
- `go-lint`
- `buildifier`
- building Buildbarn with Buildbarn

More suggestions are welcome!

**Comment by EdSchouten** [comment]
GitHub Actions based CI is now present. If this is inadequate, we should file specific issues/pull requests to improve that.
