### ISSUE TITLE
Queued operations does not seem to be sorted

### ISSUE THREAD

**Issue by perwestling** [buildbarn/bb-remote-execution#62]
This is about **in_memory_build_queue.go**

In platform queue, getNextNonBlockingOperation the first operation in the queuedOperations are returned, which would be the oldest remaining as they are added chronologically.

An operationEntry does contain priority, and the operation. 

As far as I can tell, the queuedOperationsHeap is not sorted, so if a later invocation adds a new operation with a "better" (in this case lower) priority this will still be added last in the queuedOperationsHeap.

Adding a sort to this method do solve this but this can potentially cause a large amount of shuffling in case "better" priority operations are added frequently.

This issue has also some relation to issue #38[issue #38](https://github.com/buildbarn/bb-remote-execution/issues/38) as introducing an invocation time sorting would have the same problem.

**Comment by EdSchouten** [comment]
It’s not sorted, but it is a [binary heap](https://en.m.wikipedia.org/wiki/Binary_heap). This means that extraction does always yield an operation that is minimal along a total order, right?

**Comment by perwestling** [comment]
Thanks for the quick answer, @EdSchouten. Yes, you are correct, so this issue can be closed.
