### ISSUE TITLE
Clean up queue is not sorted

### ISSUE THREAD

**Issue by perwestling** [buildbarn/bb-remote-execution#63]
This is about **in_memory_build_queue.go**

There is a clean up mechanism in the file, with a clean up queue, and also a system which uses cleanupKey to refer to the entries in the clean up queue.
Entries added to the clean up queue are added First-In-First-Out.

When the clean up queus is to be polled the following code is used:

```
func (q *cleanupQueue) run(now time.Time) {
	for len(q.heap) > 0 && !q.heap[0].timestamp.After(now) {
		heap.Pop(&q.heap).(cleanupEntry).callback()
	}
}
```
This does work fine to remove the top one in the heap when it has timed out.
But as far as I can tell there is no sorting of elements in the heap - new elements is just added at the end. So if an element with a LONG timeout is at the top, this will stop any other elements from being cleaned up.

**Comment by EdSchouten** [comment]
Similar to my response to #62, the cleanup queue is also a [binary heap](https://en.m.wikipedia.org/wiki/Binary_heap). Cleanups happen in chronological order.

**Comment by perwestling** [comment]
Thanks for the quick answer. Closing this issue.
