### ISSUE TITLE
RequestMetadata extraction does not work with Bazel

### ISSUE THREAD

**Issue by Gormo** [buildbarn/bb-remote-execution#94]
We just bumped to the latest buildbarn version in order to try out the simple action router with invocation based scheduling.

Unfortunately it seems like the InvocationId extraction is currently broken.

When checking the buildbarn scheduler GUI there is always only a single invocation Id Listed:
> { "@type": "type.googleapis.com/build.bazel.remote.execution.v2.RequestMetadata" }

Some further investigation showed that bazel does indeed send the RequestMetadata message as expected:

> ---------------------------------------------------------
> **metadata** {
>   tool_details {
>     tool_name: "bazel"
>     tool_version: "6.0.0-pre.20211117.1-2021-12-17 (@ed890679)"
>   }
>   action_id: "ee32f4898cb0cd9eee152d64360899f8422eb538364fd079827bc99e2371f81c"
>   **tool_invocation_id: "34d8cb06-d35b-49a3-a00b-53dff390d54f"**
>   correlated_invocations_id: "d5452b46-ca78-48f9-a67a-11ef39b58617"
>   action_mnemonic: "MockGen"
>   target_id: "@Fw_Framework//Framework/Api/Service:IMemProvider"
>   configuration_id: "7fe7f8dbd78a9aabed4bc3931acb7fab17e26433fb26359b5376dc8b66dcf1d2"
> }
> status {
> }
> method_name: "build.bazel.remote.execution.v2.Execution/Execute"
> details {
>   execute {
>     request {
>       instance_name: "buildbarn"
>       action_digest {
>         hash: "ee32f4898cb0cd9eee152d64360899f8422eb538364fd079827bc99e2371f81c"
>         size_bytes: 144
>       }
>     }
>     responses {
>       name: "buildbarn/operations/850f56b2-8f8c-4502-840b-a335d1fcb70d"
>       metadata {
>         type_url: "type.googleapis.com/build.bazel.remote.execution.v2.ExecuteOperationMetadata"
>         value: "\b\003\022E\n@ee32f4898cb0cd9eee152d64360899f8422eb538364fd079827bc99e2371f81c\020\220\001"
>       }
>     }
>     responses {
>       name: "buildbarn/operations/850f56b2-8f8c-4502-840b-a335d1fcb70d"
>       metadata {
>         type_url: "type.googleapis.com/build.bazel.remote.execution.v2.ExecuteOperationMetadata"
>         value: "\b\004\022E\n@ee32f4898cb0cd9eee152d64360899f8422eb538364fd079827bc99e2371f81c\020\220\001"
>       }
>       done: true
>       response {
>         type_url: "type.googleapis.com/build.bazel.remote.execution.v2.ExecuteResponse"
>         value: "\n\235\006\022\324\001\n\210\001bazel-out/pclinux64-fastbuild-fwl-nostamp/bin/external/Fw_Framework/Framework/Api/Service/Mocks/Framework/Api/Service/IMemProviderMock.c\022G\n@766c99c125bcfbade34fa491503a3f2fb4f5b9
> e7a4fc4c636d664eaa63c8a399\020\363\214\300\001\022\323\001\n\210\001bazel-out/pclinux64-fastbuild-fwl-nostamp/bin/external/Fw_Framework/Framework/Api/Service/Mocks/Framework/Api/Service/IMemProviderMock.h\022F\n@57583aaac3b8955915
> f7a7773e5929de07cdfda20aae6c67754ffc79a58c64f9\020\264\304\002J\355\002\n={\"hostname\":\"buildbarn-worker-centos7-instance\",\"thread\":\"0\"}\022\v\b\215\211\201\216\006\020\271\217\344@\032\v\b\215\211\201\216\006\020\340\345\3
> 67@\"\f\b\215\211\201\216\006\020\356\206\310\337\002*\v\b\215\211\201\216\006\020\346\312\207A2\v\b\215\211\201\216\006\020\342\306\341i:\v\b\215\211\201\216\006\020\342\306\341iB\f\b\215\211\201\216\006\020\340\211\377\265\002J\
> f\b\215\211\201\216\006\020\340\211\377\265\002R\f\b\215\211\201\216\006\020\356\206\310\337\002Zf\n>type.googleapis.com/buildbarn.resourceusage.POSIXResourceUsage\022$\n\006\020\340\263\365\256\001\022\005\020\330\305\260\030\030
> \200\340\262\r8\214]@\025P\310\026X\200=x\'\200\001\003ZC\nAtype.googleapis.com/buildbarn.resourceusage.FilePoolResourceUsageb\006\020\376\302\235\314\001*\223\001Action details (cached result): http://172.17.0.3:7984/buildbarn/bl
> obs/action/ee32f4898cb0cd9eee152d64360899f8422eb538364fd079827bc99e2371f81c-144/"
>       }
>     }
>   }
> }
> start_time {
>   seconds: 1639990413
>   nanos: 133000000
> }
> end_time {
>   seconds: 1639990413
>   nanos: 743000000
> }
> 

I added some debug printouts in in_memory_build_queue.go

```
// getRequestMetadata extracts the RequestMetadata message stored in the
// gRPC request headers. This message contains the invocation ID that is
// used to group incoming requests by client, so that tasks can be
// scheduled across workers fairly.
func getRequestMetadata(ctx context.Context) *remoteexecution.RequestMetadata {
	if md, ok := metadata.FromIncomingContext(ctx); ok {
		log.Print("Context Extraction OK")
		log.Print(md)
		for _, requestMetadataBin := range md.Get("build.bazel.remote.execution.v2.requestmetadata-bin") {
			log.Print("Parsing RequestMetadata")
			var requestMetadata remoteexecution.RequestMetadata
			if err := proto.Unmarshal([]byte(requestMetadataBin), &requestMetadata); err == nil {
				return &requestMetadata
			}
		}
	}
	log.Print("Returning nil RequestMetadata")
	return nil
}
```
And the received output is always

> Dec 20 11:25:09 buildbarn-worker-frontend-centos7-instance bb_scheduler[3339]: 2021/12/20 11:25:09 Context Extraction OK
> Dec 20 11:25:09 buildbarn-worker-frontend-centos7-instance bb_scheduler[3339]: 2021/12/20 11:25:09 map[:authority:[0.0.0.0:8982] content-type:[application/grpc] user-agent:[grpc-go/1.42.0]]
> Dec 20 11:25:09 buildbarn-worker-frontend-centos7-instance bb_scheduler[3339]: 2021/12/20 11:25:09 Returning nil RequestMetadata

So it seems like the RequestMetadata message is always lost.

I'm not too familiar with GRPC-setups so I think I might need some pointers on how to proceed with the troubleshooting from here. Any input on this? @EdSchouten ?

**Comment by EdSchouten** [comment]
Can you ensure that the gRPC client config in bb-frontend for traffic sent to the scheduler contains this?
```
forwardMetadata: ['build.bazel.remote.execution.v2.requestmetadata-bin'],
```
That's needed to make it forward the metadata to bb-scheduler.

**Comment by Gormo** [comment]
That was it! 
Just added it and everything looks a lot better!
Thank you!
